apiVersion: v1
kind: Service
metadata:
    name: app-node-service
    namespace: dev-ns
spec:
    selector:
        app: app-node
    type: NodePort
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 30001
